#!/bin/bash
n_grids="7 8 9 10 15 20 30 40 50 60 80 100 200 400 500 1000 2000 3000 4000 5000 10000"
#n_grids="7 8"
output_dir="/home/sheldon/parallel/task2/output2/"
program="./build-task2-Desktop-Debug/task2"

counter=0
for grid in $n_grids; do
    echo "grid = $grid" >> res.txt
    counter=$((counter+1))
    $program  "$output_dir"uValues_"$grid".csv "$output_dir"uValuesApproximate_"$grid".csv $grid >> res.txt 
done
